apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: standalone-collector
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: otelcol
    app.kubernetes.io/version: 0.114.0
  name: opentelemetry-demo-otelcol
  namespace: otel-demo
